### ISSUE TITLE
Yarn start not running when creating a new theme

### ISSUE THREAD

**Issue by mlpatt23** [factor1/prelude-wp#164]
`$ yarn start
yarn run v1.17.3
$ NODE_ENV=development gulp serve
[13:22:28] Using gulpfile ~/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/gulpfile.js
[13:22:28] Starting 'serve'...
[13:22:28] Starting 'cleanStyles'...
[13:22:28] Finished 'cleanStyles' after 12 ms
[13:22:28] Starting 'cleanJs'...
[13:22:28] Finished 'cleanJs' after 1.86 ms

[13:22:28] Starting 'sassTask'...
[13:22:28] 'sassTask' errored after 90 ms
[13:22:28] BrowserslistError in plugin "gulp-autoprefixer"
Message:
    Unknown browser query `maintained node versions`
Details:
    browserslist: true
    fileName: /Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/assets/scss/theme.css
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

Stack:
BrowserslistError: Unknown browser query `maintained node versions`
    at unknownQuery (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/node_modules/browserslist/index.js:117:10)
    at /Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/node_modules/browserslist/index.js:153:11
    at Array.reduce (<anonymous>)
    at resolve (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/node_modules/browserslist/index.js:121:18)
    at browserslist (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/node_modules/browserslist/index.js:217:16)
    at Browsers.parse (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/lib/browsers.js:67:16)
    at new Browsers (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/lib/autoprefixer.js:75:24)
    at plugin (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/autoprefixer/lib/autoprefixer.js:86:24)
    at LazyResult.run (/Users/melanie/Documents/Sites/test-site/app/public/wp-content/themes/f1-test-theme/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:277:20)
[13:22:28] 'serve' errored after 108 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by erwstout** [comment]
Could not replicate - will most likely close this.

**Comment by mlpatt23** [comment]
Yeah, it may have been an issue with my computer specifically
