### ISSUE TITLE
Imagemin Issues on Linux

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#46]
When installing on Ubuntu 14.04 you receive this warning along with image compression possibly failing:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
```

The image failures happen so quick and early in the build process I can't seem to scroll back up to find the errors. Going to test image compression to verify failure.

`fsevents` is specifically a OS X package, so it may not affect build.

**Comment by erwstout** [comment]
Error that is thrown when running `gulp images`:

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:367:9)
    at exports.execFile (child_process.js:139:15)
    at ExecBuffer.<anonymous> (/media/ericstout/Storage/git/prelude-test/node_modules/exec-buffer/index.js:91:3)
    at /media/ericstout/Storage/git/prelude-test/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by erwstout** [comment]
Verified similar issues on `imagemin` repository, posted issue, will wait for info / response before exploring alternative solutions for image compression.

**Comment by erwstout** [comment]
Possible Alternative: https://www.npmjs.com/package/gulp-image

**Comment by erwstout** [comment]
`"imagemin-pngquant": "^4.2.2",`

may be causing an error / mixed dependencies

**Comment by erwstout** [comment]
Install `nasm` and `autoconf` on the linux machine and verify it fixes the issue.

**Comment by erwstout** [comment]
The above does not fix issue, however Prelude is behind on `gulp-imagemin` version, will add issue to upgrade but need to verify it wont break anything before pushing live.

**Comment by erwstout** [comment]
Should retest with new `3.3.0` release..

**Comment by erwstout** [comment]
Appears to be working correctly with new updates.
